# Generated by Django 6.0 on 2026-03-21 18:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('locations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Voter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('house_no', models.IntegerField()),
                ('state', models.CharField(max_length=100)),
                ('district', models.CharField(max_length=100)),
                ('fingerprint_id', models.IntegerField(unique=True)),
                ('merkle_leaf', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('panchayat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='locations.panchayat')),
            ],
        ),
    ]
